
services:
  jupyterhub:
    build: .
    container_name: jupyterhub
    restart: always
    ports:
      - "${JUPYTERHUB_PORT}:8000"
    env_file:
      - .env
    environment:
      - DOCKER_JUPYTER_IMAGE=${DOCKER_JUPYTER_IMAGE}
      - JUPYTERHUB_ADMIN_USERS=${JUPYTERHUB_ADMIN_USERS}
      - JUPYTERHUB_NETWORK=${JUPYTERHUB_NETWORK}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./jupyterhub_config/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ${JUPYTERHUB_NETWORK}
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ${JUPYTERHUB_NETWORK}
    ports:
      - "5432:5432"

volumes:
  postgres-data:

networks:
  jupyterhub-network:
    external: true

