
services:
  jupyterhub:
    build: .
    container_name: jupyterhub
    restart: always
    ports:
      - "${JUPYTERHUB_PORT}:8000"
    env_file:
      - .env
    environment:
      - DOCKER_JUPYTER_IMAGE=${DOCKER_JUPYTER_IMAGE}
      - JUPYTERHUB_ADMIN_USERS=${JUPYTERHUB_ADMIN_USERS}
      - JUPYTERHUB_NETWORK=${JUPYTERHUB_NETWORK}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=jupyterhub-mysql
      - MYSQL_PORT=3306
    volumes:
      - ./jupyterhub_config/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ${JUPYTERHUB_NETWORK}
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: jupyterhub-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: jupyterhub
      MYSQL_USER: jupyteruser
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ${JUPYTERHUB_NETWORK}

volumes:
  mysql-data:

networks:
  jupyterhub-network:
    external: true

